import type { Metadata } from "next";
import { Alice, Spectral, Satisfy } from "next/font/google";
import type { CSSProperties } from "react";
import "./globals.css";
import Navbar from "./components/Navbar";

const alice = Alice({
  variable: "--font-alice",
  subsets: ["latin"],
  weight: ["400"],
});

const spectral = Spectral({
  variable: "--font-spectral",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const satisfy = Satisfy({
  variable: "--font-satisfy",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontFamilies = {
    "--font-alice-family": alice.style.fontFamily,
    "--font-spectral-family": spectral.style.fontFamily,
    "--font-satisfy-family": satisfy.style.fontFamily,
  } as CSSProperties;

  return (
    <html
      lang="en"
      className={`${alice.variable} ${spectral.variable} ${satisfy.variable}`}
      style={fontFamilies}
    >
      <body className={`${spectral.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
